// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { getSession } from "@/lib/session";
import AppBarConditionalRender from "@/components/layout/AppBarConditionalRender";
import SpinnerOverlay from "@/components/spinneroverlay"; // ✅ Import logo spinner

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "BrainWave",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <SpinnerOverlay /> {/* ✅ Show spinner during navigation */}
        <AppBarConditionalRender session={session}>
          {children}
        </AppBarConditionalRender>
        <Toaster position="bottom-right" reverseOrder={false} />
      </body>
    </html>
  );
}
