import type { Metadata } from "next";
import "./globals.css";
import AppBar from "./components/ui/appbar";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { getSession } from "@/lib/session";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "BrainWave",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {session && (
          <div className="flex-1/4">
            <AppBar />
          </div>
        )}
        {children}
        <Toaster position="bottom-right" reverseOrder={false} />
      </body>
    </html>
  );
}
