import type { Metadata } from "next";
import "./globals.css";
import AppBar from "./components/ui/appbar";

export const metadata: Metadata = {
  title: "BrainWave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AppBar/>
        {children}
      </body>
    </html>
  );
}
